### PR TITLE
Fixed the cards in domain page.

### PR DESCRIPTION
**Pull request by m0hit-kumar**
**Contributor** :  [Mohit Kumar](https://github.com/m0hit-kumar) 

Issues resolved:
- color of the header of the card ( .card-header  in assets/css/style.css)
- border-bottom (.card-header in assets/css/style.css)

### CODE REVIEW

**Comment by ghost** [comment]
> **Contributor** : [Mohit Kumar](https://github.com/m0hit-kumar)
> 
> Issues resolved:
> 
> * color of the header of the card ( .card-header  in assets/css/style.css)
> * border-bottom (.card-header in assets/css/style.css)

 Can you share some screenshots.

**Comment by m0hit-kumar** [comment]
image

**Comment by ghost** [comment]
> image

It seems fine. Show me once the Competitive Programming card.

**Comment by m0hit-kumar** [comment]
image

**Comment by ghost** [comment]
See, the padding of the Cyber Security and Competitive Card is not correct. The text is sticking to the bottom. Fix that please.

**Comment by m0hit-kumar** [comment]
> See, the padding of the Cyber Security and Competitive Card is not correct. The text is sticking to the bottom. Fix that please.

bottom padding right? after the Facebook

**Comment by ghost** [comment]
> > See, the padding of the Cyber Security and Competitive Card is not correct. The text is sticking to the bottom. Fix that please.
> 
> bottom padding right? after the Facebook

Yes. The card should somewhat look like this.
Screenshot 2022-01-01 at 4 29 43 PM

**Comment by m0hit-kumar** [comment]
ok no problem thanks for the feedback though

**Comment by m0hit-kumar** [comment]
image


image

image


see it now anything else needs to fix in this.

**Comment by ghost** [comment]
Perfect!

**Comment by roy-rajarshi** [comment]
Did you make a pull req for all the changes?

**Pull request merged**
